---
title: "Dr. Cindarella Petz"
subtitle: "Digital History, Historical Network Research, Text Analysis, Digital Humanities, Computational History"
---

I am a historian working at the intersection of the humanities and computer science. 
My research interests center on computational methods and the epistemological implications of the digital. In my research, I reframe historical research questions with the means of computational and multi-methodological approaches, bridging quantitative, qualitative, digital, and computational methodologies, and critically reflect their application. I consider digital literacy and computational competencies, including statistics, data modeling, digital source criticism, and tool and algorithm criticism, as key skills of today’s humanities scholarship.

In my current project as [postdoctoral researcher](https://www.ieg-mainz.de/en/institute/people/petz) at [Leibniz Institute of European History](https://www.ieg-mainz.de/), I examine historical court records computationally on the construction of political criminality, and the transformation of the former Austrian democracy to an autocracy (1933--38) in the field of digital legal history.

I am editor at [Journal of Historical Network Research (JHNR)](https://jhnr.uni.lu/index.php/jhnr/about/editorialTeam)‚ and senior convenor of the [working group "Graphs and Networks"](https://dig-hum.de/ag-graphen-netzwerke>) of the [DHd](https://dig-hum.de/), and part of the Interim Coordination Board of the ["HNR Community"](https://historicalnetworkresearch.org/) during its transitioning process. 
As part of the Local Organizing and Program Committe, I organized the [GrapHNR Conference](https://graphentechnologien.hypotheses.org/tagungen/graphentechnologien-2023) in Mainz in July 18 -- 21, 2023. 
In international cooperations, I am currently co-organizing the [Barcelona Past Networks Summer School](https://www.pastnetworks.net/) in June 25 -- 29, 2024, as well as the Session on "Networks and the Human Past" at [INSNA SUNBELT 2024](https://sunbelt2024.com/organised-sessions/) in Edinburgh in June 24 -- 30, 2024.

<!--This website was created using [Quarto](https://quarto.org/docs/websites).-->
