## Invited Talks

1. TBA, Invited Talk at Lecture Series (Prof. Dr. Julianne Nyhan), TU Darmstadt, Jan, 2026.

1. Beyond historians? LLMs and historical research, Invited Talk at Winter School ''The Future of the Past: Research Pathways in Digital Humanities and Memory Studies,'' University of Pavia, Dec 10--12, 2025, Pavia (IT).

1. GenAI. Invited Talk with Dr. Sarah Oberbichler at [''Von Büchern zu Bytes’’](https://4memory.de/aktivitaeten/veranstaltungsreihen/von-buechern-zu-bytes/)  Lecture Series, NFDI4Memory, Nov 21, 2025.

1. Buchstabensalat oder Haarknäuel? Zur Anwendbarkeit von Topic Modeling, Text Mining und Netzwerkanalyse, Invited Talk at HERMES Doktorandennetzwerk, Nov 17, 2025 (virtual).

1. LLMs as Analysis Tool: A Framework for Implementation, Evaluation and Critical Assessment. Joint Short Paper Presentation with Dr. Sarah Oberbichler at [ADHO Digital Humanities Conference ''Accessibility and Citizenship'' (DH2025)](https://dh2025.adho.org/), July 14--18, 2025, Lisbon (PORT).

1. Autokratisierung und computergestützte Analyse politischer Verfolgungspraxis. Invited Talk at [MainzedZWEI25 ''Datenlese - Was wir über Daten wissen und sie über uns''](https://www.adwmainz.de/veranstaltungen/kalender/eintrag/mainzedzwei25-datenlese-was-wir-ueber-daten-wissen-und-sie-ueber-uns-1.html) at Akademie der Wissenschaften und Literatur, Mainz, June 24, 2025.

1. Evaluating Bias Within an Epistemological Framework for AI-Based Research in the Humanities. Joint Long Paper Presentation with Dr. Sarah Oberbichler at [AIUCD2025 Conference ''Diversity, Equity, and Inclusion: Challenges and Opportunities for Digital Humanities in the Age of Artificial Intelligence’’](https://aiucd2025.dlls.univr.it/en-gb/), June 11--13, 2025, Verona (IT).

1. Analyzing political-religious criminality during the Dollfuß-/Schuschnigg-Regime -- A case study of LLM-assisted historical network research. Long Paper Presentation at [Historical Network Research Conference (HNR2025)](https://historicalnetworkresearch.github.io/riodejaneiro/), May 21--23, 2025, Rio de Janeiro (BR).

1. Lili Körbers ''Eine Jüdin erlebt das neue Deutschland'': Zensur und Strafverfolgung im ''Austrofaschismus.'' Presentation at [''Widerständiges Schreiben. Lili Körber -- Literatur, Politik und Exil’’](https://www.literaturhaus-wien.at/event/lili-koerber-tagung/) Joint Conference of Käte Hamburger Kolleg ''global dis:connect'' (LMU Munich) and österreichische Exilbibliothek at Literaturhaus Wien, November 14--15, 2024, Vienna (AT).

1. False securities: The epistemological 'virtue' of transparency and emerging uncertainties in scholarship. Presentation at [Sixth Conference on Digital Humanities and Digital History ''Exploring Epistemic Virtues and Vices: Data, Infrastructures, and Episteme between Collaboration and Exploitation,’’](https://www.c2dh.uni.lu/events/exploring-epistemic-virtues-and-vices-data-infrastructures-and-episteme-between-collaboration) C^2^DH, University of Luxembourg, March 14--16, 2024, Belval (LU).

1. Green DH and Sustainability. Invited Impulse at Fishbowl Panel Discussion at [mainzedZWEI24 ''Welche Schuhgrö{\ss}e haben wir? ökologischer Fu{\ss}abdruck und das Digitale Kulturelle Erbe’’](https://www.hs-mainz.de/event/termin/mainzedzwei24-2024-02-22-16-00-8530/) at Leibniz Zentrum für Archäologie (LEIZA), Feb 22, 2024, Mainz.

1. An Embedded Digital Humanities Framework. Invited Talk at Hands on History Lecture Series, University of Luxembourg, October 25, 2023, Belval (LU). [[Link to abstract.]](https://www.c2dh.uni.lu/de/events/embedded-digital-humanities-framework-historical-research)

1. Becoming the Digital Humanities as Discourse(s) of Subjectivation. Long Paper Presentation at [ADHO Digital Humanities 2023 ''Collaboration as Opportunity'' (DH2023)](https://dh2023.adho.org), July 10--14, 2023, Graz (AT).

1. On the shoulders of Giants. Pitfalls and challenges of a LOD network of intellectual influences. Invited Keynote at [''Network Science meets Digital History and Prosopography'' Satellite Workshop](https://sites.google.com/view/nsdhp2023/home-page) at NetSci 2023, July 11, 2023, Vienna (AT).

1. Netzwerke und Visualisierung. Potentiale der Historischen Netzwerkforschung. Invited Talk at Workshop ''Forschungsstand und -perspektiven auf die Überlieferung des Vieweg-Verlags,'' UB Braunschweig, May 03, 2023.

1. Network Models and Computational History. Analysing a Linked Open Data network. Invited Keynote at PIMO COST Action Workshop [''Conceptual and Social Networks for Movements of People across the Mediterranean Basin. Digital Methods and Application of Computational Tools and for Modelling, Analysis and Representation of Migration Phenomena,’’](https://cji.uniri.hr/pimo/) Faculty of Humanities and Social Sciences, University of Rijeka, April 04, 2023, Rijeka (HR).

1. Computational Analysis of Political Judiciary: Models, Trials, and Networks, Presentation at Forschungskolloquium at Leibniz Institute of European History Mainz (virtual), March 01, 2022.

1. LaTeX, Overleaf, and Collaborative Writing for Academics. Presentation at 60' of DH at Leibniz Institute of European History Mainz (virtual), February 22, 2022.

1. Network Models and Configurations to Conviction. Invited Talk at HNR Lunch Lecture (virtual), October 07, 2021. [[Link to lecture.]](https://www.youtube.com/watch?v=5WH1-W2VMYk)

1. A mixed methods approach to political judiciary. Presentation at Conference ''Digital Methods and Resources in Legal History" (DLH2021), Max Planck Institute for Legal History and Legal Theory (virtual), March 01--05, 2021, Frankfurt am Main. [[Link to Lecture.]](https://www.lhlt.mpg.de/dlh2021)

1. A Longitudinal Analysis of a Social Network of Intellectual History. Long Paper Presentation at IEEE/ACM International Conference on Advances in Social Network Analysis and Mining (ASONAM), (virtual) December 7--10, 2020, The Hague (NL).

1. Analyzing Political Trials during the Austrian Authoritative Rule using a Network Approach. Long Paper Presentation at SUNBELT 2020 Virtual Conference, July 20--22, 2020. 

1. Political Judiciary in the Corporate State of Austria, Long Paper Presentation at [4th European Conference on Social Networks (EUSN)](https://www.eusn2019.ethz.ch), ETH Zürich, September 9--12, 2019, Zürich (CH).

1. Networks of Political Judiciary in the Corporate State in Austria. Presentation at [13th Workshop Historical Network Research ''Networks across Time and Space. Methodological Challenges and Theoretical Concerns of Network Research in the Humanities,“](https://www.hsozkult.de/event/id/event-88842) May 27--28, 2019, Akademie der Wissenschaften und der Literatur Mainz. 

1. Gerichtsakten als Quelle historischer Netzwerkanalyse zur Politischen Verfolgung im österreichischen Ständestaat. Invited Talk at [''Von Chancen und Herausforderungen." Werkstattgespräche zur Historischen Netzwerkanalyse](https://www.hsozkult.de/event/id/event-89362), FWF-DACH-Projekt ''Issues with Europe," Forschungszentrum Digital Humanities at Innsbruck University, March 28, 2019, Innsbruck (AT). [[Link to report.]](https://www.hsozkult.de/conferencereport/id/fdkn-126843)

1. Networks of Political Prosecution. Long Paper Presentation at XXXVIII SUNBELT 2018, June 26--July 1, 2018, Utrecht (NL).


## Poster


1. Narratives of Differences and Political Judiciary in the Austrian Corporate State (1934--38). Poster Presentation, 1^st Legal Tech Munich Summer School [[Link.]](https://wwwmatthes.in.tum.de/pages/mqcx0q4yvhb7/1st-Munich-Legal-Tech-Summer-School-2021), Technical University of Munich, Aug 2--6, 2021.

1. Networks of Political Judiciary in the Corporate State: The provincial courts of Vienna in 1935. Poster Presentation, [2^nd Heidelberg Computational Humanities Summer School ''Mixed Methods in the Making" (HCH)](https://hch19.cl.uni-heidelberg.de/index.html), Heidelberg University, July 15--19, 2019. [[Link to poster.]](https://hch19.cl.uni-heidelberg.de/program/poster_pdf/poster_cindarell_petz.pdf)


## Guest Seminars

1. Modelle für die DH. Netzwerkanalyse und LLMs in der historischen Forschung. Invited Talk at ''Offenes MA-Kolloquium Digital Humanities'' (Vertretungsprofessor Dr. Anselm Küsters), Stuttgart University, June 26, 2025. [[Link to abstract.]](https://www.ilw.uni-stuttgart.de/lehre/digital-humanities/mastertagungen/ma-kolloquium-sommersemester-2025/)
 
1. Modelling Political Trials as Networks. Perks, Pitfalls, and Possibilities. Invited Talk at ''Offenes Forschungskolloquium Digital History'' (Prof. Dr. Torsten Hiltmann), Humboldt University of Berlin (virtual), Jan 19, 2022. [[Link to abstract.]](https://dhistory.hypotheses.org/1080)

1. Historical Network Research in a Nutshell: On courts, intellectuals, and the perks of networks. Invited Talk at Seminar ''Digital History" (Dr. Ute Hasenöhrl), Innsbruck University, (virtual) May 05, 2021, Innsbruck, (AT).

1. Historische Netzwerkforschung und Politische Justiz am Beispiel Wien 1935. Invited Talk at ''Oberseminar'' (PD Dr. Ulf Hashagen), Research Institute for the History of Technology and Science at the German Museum Munich, Oct 2019. 

1. Qualitative und Quantitative Textanalyse. Invited Talk at Seminar ''Computational Social Science'' (Prof. Dr. Jürgen Pfeffer), TU Munich, Nov 2019.

1. Disseminating Political Judiciary with ERGM. Invited Talk at ''Kolloquium'' (Prof. Dr. Christoph Stadtfeld), ETH Zürich, May 2019, Zürich (CH). 

1. Qualitative und Quantitative Textanalyse. Invited Talk at Seminar ''Computational Social Science'' (Prof. Dr. Jürgen Pfeffer), TU Munich, Nov 2018.
